name: Gameboy tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3 make git pkg-config
        cargo install cbindgen
    - uses: libsdl-org/setup-sdl@v1
      with:
        version: 3.2.30
        install-linux-dependencies: true
        cmake-arguments: -DSDL_UNIX_CONSOLE_BUILD=ON
    - name: Runs tests
      run: make test
